spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username:
      postgres 
    password:
      postgres 
  jpa:
    hibernate:
      ddl-auto:
        update
  redis:
      host: localhost
      port: 6379
      password: password
  cache:
      type: redis
